server:
  port: 1113

eureka:
  instance:
    hostname: peer1
    instance-id: eurekaRegister:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://eurekaRegister:zhangshuai@peer2:1112/eureka

spring:
  application:
    name: eureka-server

