server:
  port: 1112

eureka:
  instance:
    hostname: peer2
    instance-id: eurekaRegister:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://eurekaRegister:zhangshuai@peer1:1113/eureka

spring:
  application:
    name: eureka-server

