server:
  port: 1112

eureka:
  instance:
    hostname: peer1
    instance-id: 127.0.0.1:${server.port}
    metadata-map:
      # [HA-P配置]-当前服务实例的zone
      zone: ${SERVER_ZONE:bj-1}
      #config bus refresh index
      index: ${spring.application.index:127.0.0.1}
  client:
    # [HA-P配置]-当前服务实例的region
    region: ${SERVER_REGION:cn-bj}
    # [HA-P配置]-开启当前服务实例优先发现同zone的注册中心，默认为true
    prefer-same-zone-eureka: true
    # [HA配置]-可用zone内注册中心地址列表
    availability-zones:
      cn-bj: ${eureka.instance.metadata-map.zone:bj-1}
    serviceUrl:
      bj-1: http://eurekaRegister:zhangshuai@peer1:1112/eureka/,http://eurekaRegister:zhangshuai@peer2:1113/eureka/
#      defaultZone: http://eurekaRegister:zhangshuai@peer2:1112/eureka
#      defaultZone: http://eurekaRegister:zhangshuai@peer1:1112/eureka/,http://eurekaRegister:zhangshuai@peer2:1113/eureka/

spring:
  application:
    name: eureka-server1

