server:
  port: 1111

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    # [服务续约]-服务续约任务调用的间隔时间，默认为30s
    lease-renewal-interval-in-seconds: 5
    # [服务续约]-心跳检查之服务失效时间，默认为90s，这个配置一般为lease-renewal-interval-in-seconds的三倍！
    lease-expiration-duration-in-seconds: 15
#    metadataMap:
#      zone: default
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
    # [服务续约]-当前服务实例更新注册服务缓存清单的更新间隔时间，默认为30s，一般和lease-renewal-interval-in-seconds保持一致！
    registry-fetch-interval-seconds: 10
    # 只能属于一个region,不配置默认
#    region: default
#     可设置多个，与region是一对多关系，逗号分隔
#    availability-zones: default
  server:
    # 是否开启保护机制
    enable-self-preservation: false

spring:
  freemarker:
    #是否优先从文件系统加载template，以支持热加载，默认为true，eureka管理界面开启应关闭此选项
    prefer-file-system-access: false
  security:
#    basic:
      #启用基本身份认证:高版本已丢弃
#      enabled: true
    user:
      name: eurekaRegister
      password: zhangshuai

app:
  id: sentinel-apollo

apollo:
  bootstrap:
    enabled: true
    # 该配置文件指定多namespaces 或通过 @EnabledApolloConfig({"application","operation-config"}) 激活
    namespaces: application-sentinel-apollo
  cluster: default
  meta: ${APOLLO_META:http://dev.config.apollo.letv.com}
  cacheDir: /letv/app/mas/caller/apollo-cache